# fly.toml app configuration file generated for poliplanner2 on 2025-12-16T11:02:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poliplanner2'
primary_region = 'gru'

[build]
  [build.args]
    GO_VERSION = '1.24.0'

[env]
  APP_ENV = 'prod'
  SERVER_ADDR = ':8080'
  # This is not really a concern because they have to have access to the entire server to
  # access this, from where whe are fucked up
  DATABASE_URL = '/poliplanner/poliplanner.db'
  APP_BASE_DIR = '/var/poliplanner'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256

[mounts]
  source = "poliplanner2"
  destination = "/poliplanner"
